# EXPLORATARY DATA ANALYSIS
##### (EDA – BUSINESS PROBLEM SOLVING)

In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns

In [5]:
# read dataset
retail_store = pd.read_csv('final_retail_store_clean_dataset.csv')

In [15]:
total_sales = retail_store['Sales'].sum()
total_profit = retail_store['Profit'].sum()
profit_margin = total_profit / total_sales

print(f"total_sales is = {total_sales}\ntotal_profit is = {total_profit}\nprofit_margin is = {profit_margin}")

total_sales is = 2297200.8603
total_profit is = 286397.0217
profit_margin is = 0.12467217240315605

In [16]:
# CATEGORY PERFORMANCE
retail_store.groupby('Category')[['Sales' , 'Profit']].sum().sort_values(by='Profit',ascending=False)

                       Sales       Profit
Category
Technology       836154.0330  145454.9481
Office Supplies  719047.0320  122490.8008
Furniture        741999.7953   18451.2728

In [30]:
# YEARLY SALES TREND
retail_store.groupby('order_year')[['Sales']].sum()

                  Sales
order_year
2014        484247.4981
2015        470532.5090
2016        609205.5980
2017        733215.2552

In [32]:
# MONTHLY SALES TREND
retail_store.groupby(['order_month'])[['Sales']].sum()

                   Sales
order_month
1            161083.5874
2            132721.3594
3            220064.6460
4            147031.2641
5            166420.3167
6            144883.4973
7            161227.1045
8            209964.3679
9            248989.3031
10           184356.3342
11           271693.7525
12           248765.3272

In [26]:
retail_store.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'order_year',
       'order_month', 'Order_Day', 'delivery_days', 'profit_margin'],
      dtype='str')

In [29]:
# TOP 10 PRODUCTS BY SALES
retail_store.groupby('Product Name')[['Sales']].sum().sort_values(by='Sales' , ascending=False).head(10)

                                                        Sales
Product Name
Canon imageCLASS 2200 Advanced Copier               61599.824
Fellowes PB500 Electric Punch Plastic Comb Bind...  27453.384
Cisco TelePresence System EX90 Videoconferencin...  22638.480
HON 5400 Series Task Chairs for Big and Tall        21870.576
GBC DocuBind TL300 Electric Binding System          19823.479
GBC Ibimaster 500 Manual ProClick Binding System    19024.500
Hewlett Packard LaserJet 3310 Copier                18839.686
HP Designjet T520 Inkjet Large Format Printer -...  18374.895
GBC DocuBind P400 Electric Binding System           17965.068
High Speed Automatic Electric Letter Opener         17030.312

In [35]:
# TOP 10 LOSS MAKING PRODUCTS BY SALES
retail_store.groupby(['Product Name'])[['Sales']].sum().sort_values(by='Sales').head(10)

                                                    Sales
Product Name
Eureka Disposable Bags for Sanitaire Vibra Groo...  1.624
Avery 5                                             5.760
Xerox 20                                            6.480
Grip Seal Envelopes                                 7.072
Avery Hi-Liter Pen Style Six-Color Fluorescent Set  7.700
Avery Hi-Liter Comfort Grip Fluorescent Highlig...  7.800
Xerox 1989                                          7.968
4009 Highlighters                                   8.040
Stockwell Gold Paper Clips                          8.096
Newell 308                                          8.400

In [36]:
retail_store.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'order_year',
       'order_month', 'Order_Day', 'delivery_days', 'profit_margin'],
      dtype='str')

In [43]:
# HIGH SALES BUT LOSS
temp = retail_store.groupby('Sub-Category')[['Sales' , 'Profit']].sum()
temp[(temp['Sales'] > 100000) & (temp['Profit']<0)]

                    Sales      Profit
Sub-Category
Bookcases     114879.9963  -3472.5560
Tables        206965.5320 -17725.4811

In [44]:
# DISCOUNT IMPACT
retail_store[['Discount' , 'Profit']].corr()

          Discount    Profit
Discount  1.000000 -0.219487
Profit   -0.219487  1.000000

In [48]:
# SHIP MODE ANALYSIS
retail_store.groupby('Ship Mode')['Profit'].mean().sort_values(ascending=False)

Ship Mode
First Class       31.839948
Second Class      29.535545
Same Day          29.266591
Standard Class    27.494770
Name: Profit, dtype: float64

In [58]:
retail_store.groupby('Region')[['Sales' , 'Profit']].sum().sort_values(by='Sales')

               Sales       Profit
Region
South    391721.9050   46749.4303
Central  501239.8908   39706.3625
East     678781.2400   91522.7800
West     725457.8245  108418.4489

In [53]:
retail_store.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

In [59]:
retail_store.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
order_year         int64
order_month        int64
Order_Day          int64
delivery_days      int64
profit_margin    float64
dtype: object